version: 2.1

jobs:
  sonarqube:
    docker:
      - image: sonarsource/sonar-scanner-cli
    resource_class: small
    steps:
      - checkout
      - run: cd ../BACKEND/package.json
      - run: npm start
      - run: npm test-api
      - attach_workspace:
          at: ~/workspace
workflows:
  version: 2
  sonar_workflow:
    jobs:
      - sonarqube
