version: 2.1

jobs:
  sonarqube:
    docker:
      - image: sonarsource/sonar-scanner-cli
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd ../BACKEND
            npm install
      - run:
          name: Start Application
          command: npm start
      - run:
          name: Run Newman tests
          command: newman run ../APDSPOE.postman_collection.json -e ../APDS_POE.postman_environment.json --reporters cli,junit
      - attach_workspace:
          at: ~/workspace

workflows:
  version: 2
  sonar_workflow:
    jobs:
      - sonarqube
